name: CI Tests

on: [pull_request, push]

jobs:
  bootstrap:
    name: Quick tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # - name: Install lerna
    #   run: yarn global add lerna

    - name: Bootstrap
      if: steps.cache.outputs.cache-hit != 'true'
      run: npx lerna bootstrap

    # - name: Check types
    #   run: $(yarn global bin)/lerna run check-types

    # - name: Lint
    #   run: $(yarn global bin)/lerna run lint

    # - name: Unit tests
    #   run: $(yarn global bin)/lerna run test:unit

    # - name: Coverage
    #   run: $(yarn global bin)/lerna run coverage

    # - name: E2e tests
    #   run: $(yarn global bin)/lerna run test:e2e

    # - name: Spec tests
    #   run: $(yarn global bin)/lerna run test:spec-min